### ISSUE TITLE
Description on java pipeline jar structure

### ISSUE THREAD

**Issue by abelsromero** [gaia-pipeline/docs#7]
I am testing gaia locally and I could integrate the https://github.com/gaia-pipeline/java-example in no time and play a bit with it 👍 

But the issue is that I could not find detailed info on what gaia expects to create the pipeline so I can create pipelines with other JVM languages and tools like gradle (if that's currently possible).

**Comment by michelvocks** [comment]
Welcome @abelsromero 🤗 
We are lacking here documentation, you are absolutely right. I hope we can fix that in the near future.

To answer your question: Currently, only Maven is supported. Gaia only needs maven 3 & jdk (at least 1.8). The `Dockerfile` for Gaia-Java image is usually a good starting point: https://github.com/gaia-pipeline/gaia/blob/master/docker/Dockerfile.java

I will close this issue now but feel free to reopen it in case you have any questions left. 😃

**Comment by abelsromero** [comment]
> We are lacking here documentation, you are absolutely right. I hope we can fix that in the near future.

No problem at all :+1:, but I need to understand some details to see what can and cannot be done.
Looking into the code I found [this](https://github.com/gaia-pipeline/gaia/blob/a1cbf4984e6aa240f7069eb79889ba5b5a27d17f/workers/pipeline/build_java.go#L60) and [this](https://github.com/gaia-pipeline/gaia/blob/a1cbf4984e6aa240f7069eb79889ba5b5a27d17f/workers/pipeline/build_java.go#L21) which confirms my initial ideas.
This means the pipeline definition must adhere to some specific rules.

**Comment by michelvocks** [comment]
Yes, right. The build process expects at the end a full containing jar. You can find that definition also in the pom.xml file: https://github.com/gaia-pipeline/java-example/blob/master/pom.xml
